// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf9p63pp7QK5lSe1OrGBB2lbmkabTcNUQ',
    appId: '1:981845180527:web:0a2ddc88ce7776d8354d9a',
    messagingSenderId: '981845180527',
    projectId: 'bada-kids',
    authDomain: 'bada-kids.firebaseapp.com',
    storageBucket: 'bada-kids.appspot.com',
    measurementId: 'G-R39VYTWN2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnZdjq5L6cUBIc8xip-3gPko05QSXki2M',
    appId: '1:981845180527:android:22ea5ca187a74091354d9a',
    messagingSenderId: '981845180527',
    projectId: 'bada-kids',
    storageBucket: 'bada-kids.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyKG5h-V7PwEuYkxtBqMNWjDnh7hmggBI',
    appId: '1:981845180527:ios:6c41d516189197fb354d9a',
    messagingSenderId: '981845180527',
    projectId: 'bada-kids',
    storageBucket: 'bada-kids.appspot.com',
    iosBundleId: 'com.example.badaKidsFront',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyKG5h-V7PwEuYkxtBqMNWjDnh7hmggBI',
    appId: '1:981845180527:ios:ec21426e6a90c900354d9a',
    messagingSenderId: '981845180527',
    projectId: 'bada-kids',
    storageBucket: 'bada-kids.appspot.com',
    iosBundleId: 'com.example.badaKidsFront.RunnerTests',
  );
}
